
title: Xavag3djang0's Blog
description: "Testing The Boundaries"
author: 
  name: "Xavag3djang0"
  email: "lonestoner001@gmail.com"
  url: "https://xavag3djang0.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Xavag3djang0"
year : "2020"
